### ISSUE TITLE
"Closures" section has only one line.

### ISSUE THREAD

**Issue by kberov** [hankache/perl6intro#103]
I see that we have only one line about closures copied from the official documentation.
I would suggest that we copy at least the first example from there, thus explaining the matter.
https://docs.perl6.org/language/functions#Closures

``` perl6
sub generate-sub($x) {
    my $y = 2 * $x;
    return sub { say $y };
    #      ^^^^^^^^^^^^^^  inner sub, uses $y
}
my $generated = generate-sub(21);
$generated(); # 42
```

Here $y is a lexical variable inside generate-sub, and the inner subroutine that is returned uses it. By the time that the inner sub is called, generate-sub has already exited. Yet the inner sub can still use $y, because it closed over the variable.

**Comment by hankache** [comment]
@kberov I do not have any objections regarding adding an example for closures.  
That being said, I am not very fond of the example used in the official docs and would rather use something simpler for new users to understand.
```perl6
my $name = "John Doe";
sub greet {
  return "Good Morning $name";
}
say greet;
```

**Comment by kberov** [comment]
But the example in the official docs demonstrates the topic completely and is only two lines longer. Otherwise we do not explain much.
In the official docs the example demonstrates exactly how a subroutine closes over a variable which is not any more in scope. The variable is gone, not visible, but the subroutines (stored in a variable) sees it.
In your example the variable is still visible.

**Comment by hankache** [comment]
@kberov I do agree that the example that I gave in my previous comment is cheating :) I didn't want to immerse the new users in complex definitions. This is why I initially just stated that all objects are closures without getting into details.

That being said, if you think that it's better to get into details when it comes to this subject, I drafted a new section for closures that we could include: https://gist.github.com/hankache/d5421b3d95c792419117b0dd9690106f

I heavily plagiarized the examples from https://developer.mozilla.org/en/docs/Web/JavaScript/Closures#Closure :)

@lizmat what do you think?

**Comment by kberov** [comment]
@hankache You went even one step further of what I expected as enough minimum.
The enough minimum was the copy/pasted text from https://docs.perl6.org/language/functions#Closures above. I would be happy even if we literary used only this text
So choose what you think is better. :+1:

**Comment by kberov** [comment]
Great! Thanks @hankache . I will modify the translation accordingly next week.
