### ISSUE TITLE
Mention rlwrap or Linenoise at the top

### ISSUE THREAD

**Issue by uvtc** [hankache/perl6intro#16]
To get a repl that has working command line editing, either mention use of rlwrap (install rlwrap, then run perl6 like, `rlwrap perl6`), or else usage of the Linenoise module.

**Comment by uvtc** [comment]
Wait. Hmm. Looks like there may be activity going on (@hoelzro) to obviate the need for this:
<https://github.com/rakudo/rakudo/commit/5dacb112935412a5039ad6382361b8320bb49d99>

**Comment by uvtc** [comment]
Whoops. Accidentally closed. Will leave that for you, since it still may be something to include for a while. Not sure.

**Comment by hoelzro** [comment]
@uvtc The `Readline` support I added just means that `perl6` will use `Readline` if it's available; due to licensing, we can't distribute `Readline` with Rakudo

**Comment by uvtc** [comment]
Hi, @hoelzro . I'm on Debian Testing here. Just `rm -f`'d my ~/.rakudobrew and ~/.perl6 dirs. Made sure I have libreadline-dev installed (which gives me libreadline6). I then reinstalled via rakudobrew and did a `rakudobrew build moar`. Fired up the repl, but still no command-line editing.

Aside: for now, command-line editing works fine with `rlwrap perl6` (no tab-completion, but that's ok).

**Comment by hoelzro** [comment]
@uvtc Unless you `panda install Linenoise` or `panda install Readline`, the REPL won't include a line editor.  The support in the REPL just means they'll be used if available.

**Comment by uvtc** [comment]
@hoelzro Oh! Ok. Did `rakudobrew build-panda`, then `panda install Readline`.

Now just running `perl6` gives me a repl with command-lined editing. Thanks!

@hankache In that case, maybe include `anda install Readline` under your section 1.3.

**Comment by hankache** [comment]
@hoelzro @uvtc wouldn't it be better to propose Linenoise instead of Readline, taking into consideration Windows users? Since the C files are distributes with Linenoise it would make their life easier, unless I am missing something. What do you think?

**Comment by uvtc** [comment]
Sorry, I don't know anything about the setup on MS Windows (or Mac OS X for that matter).

Before @hoelzro 's commit, I didn't know about Readline and thought the only options were Linenoise or rlwrap (and rlwrap "just worked"™ for me, so I used that).

Seems fine to have different recommendations for each OS. Since Readline is so common/standard on GNU/Linux, makes sense (IMO) to use that there and not reinvent the wheel.

**Comment by hankache** [comment]
The latest commit updates section 1.4 that adds info on how to enable line editing.

**Comment by uvtc** [comment]
:+1:
