### ISSUE TITLE
example doesn't compile

### ISSUE THREAD

**Issue by bmusin** [hankache/perl6intro#161]
Hi. Going through your [tutorial][tut].
```
my $a;
my $b;
$b := $a;
```
Last line doesn't compile.
![image](https://user-images.githubusercontent.com/9249387/34953157-14b34a14-fa2d-11e7-84b7-8ae393b62f26.png)

My perl version:
```
This is Rakudo Star version 2017.10 built on MoarVM version 2017.10
implementing Perl 6.c.
```
[tut]: http://perl6intro.com/#_assignment_vs_binding

**Comment by lizmat** [comment]
Hi Bulat,

> On 15 Jan 2018, at 17:48, Bulat Musin <notifications@github.com> wrote:
> my $a;
> my $b;
> $b := $a;
> 
> Last line doesn't compile.

Indeed, but this is an artefact of using the REPL.

If you try to do this on a single line:

> my $a; my $b; $b := $a

then it *will* work as documented.


HTH


Elizabeth Mattijsen


BTW, this type of question is probably better asked on:

- StakOverflow: https://stackoverflow.com/questions/tagged/perl6
- perl6-users mailing list
- #perl6 IRC channel on irc.freenode.org

**Comment by bmusin** [comment]
Thanks you.
