### ISSUE TITLE
Could you please add Russian language?

### ISSUE THREAD

**Issue by Alihusejn** [hankache/perl6intro#184]

**Comment by hankache** [comment]
Hi @Alihusejn, thank you for your interest in perl6intro.

A Russian translation need to be contributed by someone other than me since I don't know Russian.

Do you know someone who might be able to do it? Maybe yourself if you feel like it?

**Comment by Altai-man** [comment]
@hankache ping.
My Russian is native, but unfortunately this month is really cruel regarding how much time I can spend on things.
I can probably do that, also fund some folks who are good with writing and do some research about appropriate IT/Perl terms(based on how other translators did), etc. It won't be too quick, but I will ping you when anything will be ready. :)

I guess you can assign me for this issue.

**Comment by hankache** [comment]
@Altai-man Perfect!!

Best of luck!

**Comment by Altai-man** [comment]
Some guidance is needed:

https://perl6intro.com/#_unicode_aware_operations - what is the meaning of "Strings" section's content? It is not very clear, what are those "generic string operations"? How it ties to "comparing or sorting", aren't those quite generic operations on string arrays?

**Comment by hankache** [comment]
Hi,

By generic I meant the usual operators ie. cmp & sort. The message that I was trying to convey is that using the same old operators / the ones everyone is used to (sort and cmp) on UTF8 strings will yield results that the user isn't expecting. Alternatively we can use unicode aware ops like collate and unicmp to get the desired result.

If the word generic is misleading or the sentence needs rewording, I am more than happy to do it.

Great job on the first draft, that was quick!
