### ISSUE TITLE
Please use HTTPS

### ISSUE THREAD

**Issue by zoffixznet** [hankache/perl6intro#185]
Looks like newer browsers report site as insecure when you try to visit it, as reported by one of the users here (possibly using HTTPS-everywhere plugin): https://twitter.com/shniperson2/status/1008996718912987136

Even though the site doesn't handle any sensitive info, not using HTTPS still puts users at risk as malicious agent can inject unwanted stuff into the page, such at bitcoin miners or an invitation for the user to install a malicious piece of software, which they might, because they trust your site.

These days it's pretty easy to get a cert from Let's Encrypt and you can manage it easily with tools like [Certbot](https://certbot.eff.org/)

**Comment by hankache** [comment]
@zoffixznet That's because p6weekly put the link as https://perl6intro.com instead of http.

Normally if the link is http://perl6intro.com you shouldn't get any warning.

Nonetheless I am keeping this issue open because using an SSL cert is a good way forward.

**Comment by hankache** [comment]
@zoffixznet thank you for spotting this.

**Comment by hankache** [comment]
@zoffixznet perl6intro.com is now using https
