### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by kolikov** [hankache/perl6intro#31]
For french Translation:

Replace the term **'sous-programme'** par **'routine'** ou **'sous-routine'** , which is used more often in French.
If resolved, I will do it in my next commit/pull request ...
Thanks.

**Comment by hankache** [comment]
@kolikov Spot on! Go with whatever you feel is more appropriate. Honestly "**sous-programme**" (est lourd comme mot) so I'd rather we use something else.

**Comment by kolikov** [comment]
Ok, will do ... Thanks.

A la semaine prochaine !
