### ISSUE TITLE
Introducing subs a little more clearly?

### ISSUE THREAD

**Issue by MattOates** [hankache/perl6intro#4]
7.1. Definition

The π is a constant Num in Perl 6 this section kind of makes that a bit confusing, especially as τ is also conceptually a constant rather than a function in maths too. I'm not really convinced showing people a maths symbol name for a sub is the most obvious either for a first example. If you really wanted to show unicode support why not a cat emojii that says meow? Or something equally dumb but perhaps a little less obtuse? Especially as the next signature example is a hello person example anyway?

**Comment by hankache** [comment]
Hi Matt, You're absolutely right. I think we need another example for subs.

I think unicode support would better fit in a chapter on its own.

What do you think?

Thank you for your feedback :)

**Comment by hankache** [comment]
Example changed.
Added a new unicode chapter
