### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by hankache** [hankache/perl6intro#41]
@titsuki can you kindly update:

- Line 1 The translation of "introduction" in "Perl 6 Introduction"

- Line 12 The translation of "Table of Content"

- Some examples could be modified to use Japanese letters and showcase unicode support. So for example instead of `say "Hello World";` you can use `say "こんにちは世界"; ` etc. Assuming this is how you write hello world in Japanese. I just used Google translate ;)

**Comment by hankache** [comment]
@titsuki  by the way the translation is live on http://ja.perl6intro.com

**Comment by titsuki** [comment]
@hankache
Thanks for building the web page! 
I'll fix it later.

**Comment by hankache** [comment]
@titsuki Thanks,and well done!
