### ISSUE TITLE
Syntax errors in NOTE: or WARNING: lines in Japanese document

### ISSUE THREAD

**Issue by titsuki** [hankache/perl6intro#46]
It is the wrong way to write "注釈:" instead of "NOTE:" or  "警告:" instead of "WARNING:"

**example (valid cases)**
```
NOTE: For the complete list of operators, including their precedence, go to http://doc.perl6.org/language/operators
```

```
WARNING: The regex used in this example for email validation is not very accurate. +
Its sole purpose is to demonstrate regex functionality in Perl 6. +
Do not use it as-is in production.
```

**Comment by hankache** [comment]
@titsuki yes NOTE: and WARNING: and INFO: should be left as is and not translated because they are keywords used for rendering.

**Comment by titsuki** [comment]
@hankache
Thanks for your advice and sorry for my many mistakes...

**Comment by hankache** [comment]
@titsuki No worries. Thank you for taking the time to correct issues.
